project:
  type: website

# website:
#   title: "Time Series - Natalie Smith"
#   navbar:
#     collapse: true
#     scroll: true
#     left:
#       - text: "About Me"
#         file: index.qmd
#       - introduction.qmd
#       - data-sources.qmd
#       - data-visualization.qmd
#       - eda.qmd
#       - autoregressive-models.qmd
#       - arimax.qmd
#       - financial-models.qmd
#       - deep-learning.qmd
#       - conclusions.qmd
#       - references.qmd

website:
  title: "Time Series - Natalie Smith"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "About Me"
        contents: 
        - index.qmd
      - section: "Introduction"
        contents:
        - introduction.qmd
      - section: "Data"
        contents:
        - data-sources.qmd
        - data-visualization.qmd
        - eda.qmd
      - section: "Modeling and Methods"
        contents:
        - autoregressive-models.qmd
        - arimax.qmd
        - financial-models.qmd
        - deep-learning.qmd
      - section: "Conclusions"
        - conclusions.qmd
      - section: "References"
        - references.qmd

      
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

