project:
  type: website

website:
  title: "Time Series - Natalie Smith"
  navbar:
    left:
      - text: "About Me"
        file: index.qmd
      - introduction.qmd
      - data-sources.qmd
      - data-visualization.qmd
      - eda.qmd
      - autoregressive-models.qmd
      - arimax.qmd
      - financial-models.qmd
      - deep-learning.qmd
      - conclusions.qmd
      - references.qmd
      
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

