project:
  type: website

website:
  title: "Natalie Smith"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - introduction.html

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

