project:
  type: website

website:
  title: "Natalie Smith"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - introduction.qmd
      - data-sources.qmd
      - data-visualization.qmd
      - eda.qmd
      - autoregressive-models.qmd
      - spectral.qmd
      - financial-models.qmd
      - deep-learning.qmd
      - conclusions.qmd
      
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

