project:
  type: website

website:
  title: "Natalie Smith"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - about.qmd

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

