---
#title: "Data Visualization"
headertext: "Data Visualization"
format: 
  html:
    theme: lux
---



```{r ,echo=FALSE, message=FALSE, warning=FALSE}
library(flipbookr)
library(tidyverse)
library(ggplot2)
library(forecast)
library(astsa) 
library(xts)
library(tseries)
library(fpp2)
library(fma)
library(lubridate)
library(tidyverse)
library(TSstudio)
library(quantmod)
library(tidyquant)
library(plotly)
library(ggplot2)
```

```{r, echo=FALSE}

options("getSymbols.warning4.0"=FALSE)
options("getSymbols.yahoo.warning"=FALSE)

tickers = c("XOM","CVX","SHEL")
for (i in tickers){
  getSymbols(i,
             from = "2012-10-01",
             to = "2022-12-01")}

x <- list(
  title = "date"
)
y <- list(
  title = "value"
)

stock <- data.frame(XOM$XOM.Adjusted,
                    CVX$CVX.Adjusted,
                    SHEL$SHEL.Adjusted)


stock <- data.frame(stock,rownames(stock))
colnames(stock) <- append(tickers,'Dates')

stock$date<-as.Date(stock$Dates,"%Y-%m-%d")
head(stock)
```


```{r, echo=FALSE}
ggplot(stock, aes(x=date)) +
  geom_line(aes(y=XOM, colour="XOM"))+
  geom_line(aes(y=CVX, colour="CVX"))+
  geom_line(aes(y=SHEL, colour="SHEL"))+
   labs(
    title = "Stock Prices for Oil and Gas Companies",
    subtitle = "From 2013-2022",
    x = "Date",
    y = "Adjusted Closing Prices")+
    theme(panel.background = element_rect(fill = "white", colour = "grey50"))+
    guides(colour=guide_legend(title="Oil and Gas Companies")) 

```

Hover over the plot to see the difference.
 
```{r}
g4<- ggplot(stock, aes(x=date)) +
  geom_line(aes(y=XOM, colour="XOM"))+
  geom_line(aes(y=CVX, colour="CVX"))+
  geom_line(aes(y=SHEL, colour="SHEL"))+
   labs(
    title = "Stock Prices for the Oil and Gas Companies",
    subtitle = "From 2013-2022",
    x = "Date",
    y = "Adjusted Closing Prices")+
    guides(colour=guide_legend(title="Oil and Gas Companies")) 


ggplotly(g4) %>%
  layout(hovermode = "x")
```








