---
title: "Introduction"
format: 
  html:
    theme: lux
---

### **Background**

Over the last 100 years, the impact of climate change on the world's ecosystem has been observed in a variety of different areas, including new record-high temperature increases year after year, droughts, loss of wildlife habitats and resources, more frequent and severe natural disasters and storms, worsening air quality, and more, much of which is still yet to seen in the coming decades. 

In the United States, scientists are often looking at Florida when observing both current and future consequences of climate change, most notably rapid sea level rise and increased flooding that make the southern, peninsular state particularly vulnerable. Many areas of southern Florida, especially extremely popular and historic cities like Miami Beach and landmarks like the Florida Keys, are even theorized to be partially or completely submerged underwater within decades without human intervention to rapidly protect infrastructure [1]. 

### **Guiding Questions for Analysis**

In this project, I will be using time series analysis to study the the current consequences of climate change and predict its potential impacts on the future by zooming in on the state of Florida and answering the following questions:

  1. How has Florida's temperature changed over the last few decades?
      i) Have averages temperatures continued to trend upwards?
      ii) Is Florida experiencing consistent record-high temperatures in the summer year after year?
  2. Is Florida seeing consistent temperature increases in every season compared to previous years?
      i) For example, are winters in Florida in the 2010s and 2020s consistently hotter than the Florida winters of previous decades?
  3. Can current climate data be used to predict future temperature trends in Florida in the coming decades?

  4. Has precipitation in Florida changed over the last few decades? Is the state seeing increased, decreased, or relatively constant levels of rain year after year?
  
  5. Is precipitation in Florida more common in some months than others?

  6. Have the number hurricanes and tropical storms affecting the state changed over the last few decades?

  7. Has the intensity and damage caused by major storms (particularly hurricanes and tropical storms) affecting the state increased?

  8. Has flooding overall in coastal Floridian cities and town changed over the years?

  9. Has the cost of repairing damage done by major storms, storm surge, and flooding increased over the last few decades?

  10. How has climate change affected the cost of homes, home insurance, and/or flood insurance in coastal Floridian cities and towns?

  11. What is the extent to which Florida's coastline has receded over the decades?
      i) Is the state experiencing coastal erosion at a faster pace than in previous decades?
      ii) How rapidly are local sea levels rising?