---
title: "References"
format: 
  html:
    theme: lux
---

### **Data Sources:**

1.  NHE Historical and Projections - Data. CMS. (n.d.). Retrieved from <https://www.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/NationalHealthExpendData/NationalHealthAccountsProjected>
2.  Yahoo! (n.d.). IShares U.S. pharmaceuticals ETF (IHE) stock price, news, quote & history. Yahoo! Finance. Retrieved from <https://finance.yahoo.com/quote/IHE?p=IHE>
3.  Centers for Disease Control and Prevention. (n.d.). Weekly U.S. Influenza Surveillance Report. Centers for Disease Control and Prevention. Retrieved from <https://www.cdc.gov/flu/weekly/index.htm#FluSurvNet>

### **Article References:**

1.  McAuliff, M. (2020, October 1). Sky-high drug prices driven by pharma profits, House dems charge. KFF Health News. Retrieved from <https://kffhealthnews.org/news/sky-high-drug-prices-driven-by-pharma-profits-house-dems-charge/>

2.  Carroll, A. E. (2022, July 7). What's wrong with health insurance? deductibles are ridiculous, for starters. The New York Times. Retrieved from <https://www.nytimes.com/2022/07/07/opinion/medical-debt-health-care-cost.html>

3.  Hananel Director, S., Hananel, S., Director, Gordon Director, P., Gordon, P., Manager, N. F. S., Fowler, N., Manager, S., Jarsulic, M., Wong, T. K., Chang, R., & Olinsky, B. (n.d.). How big pharma reaps profits while hurting everyday Americans. Center for American Progress. Retrieved from <https://www.americanprogress.org/article/big-pharma-reaps-profits-hurting-everyday-americans/>

4.  Proclinical.com. (n.d.). Retrieved from <https://www.proclinical.com/blogs/2022-6/who-are-the-top-10-pharma-companies-in-the-world-2022>

5. How the ACA has affected prescription access and affordability. (n.d.). Retrieved from <https://www.goodrx.com/hcp/providers/aca-impact-prescription-access>
